export class I129Model {
  page_1_1_FamilyName: string;
  page_1_1_GivenName: string;
  page_1_1_MiddleName: string;
  page_1_2_CompanyorOrganizationName: string;
  page_1_3_InCareOfName: string;
  page_1_3_StreetNumberandName: string;
  page_1_3_Apt: boolean = false;
  page_1_3_Ste: boolean = false;
  page_1_3_Flr: boolean = false;
  page_1_3_Number: string;
  page_1_3_CityorTown: string;
  page_1_3_State: string;
  page_1_3_ZIPCode: string;
  page_1_3_Province: string;
  page_1_3_PostalCode: string;
  page_1_3_Country: string;
  page_1_4_DaytimeTelephoneNumber: string;
  page_1_4_MobileTelephoneNumber: string;
  page_1_4_EmailAddress: string;
  page_1_5_FederalEmployerIdentificationNumber: string;
  page_1_5_InduvidualIRSTaxNumber: string;
  page_1_5_USSocialSecurityNumber: string;
  page_2_1_RequestedNonimmigrantClassification: string;
  page_2_2_Newemployment: boolean = false;
  page_2_2_Continuationofpreviouslyapprovedemploymentwithoutchangeswiththesameemployer: boolean = false;
  page_2_2_Changeinpreviouslyapprovedemployment: boolean = false;
  page_2_2_Newconcurrentemployment: boolean = false;
  page_2_2_changeofemployer: boolean = false;
  page_2_2_Amendedpetition: boolean = false;
  page_2_3_ProvidethemostresentpetitionapplicationreseiptnumberforthebeneficiaryIfnoneindicateNone: string;
  page_2_4_NotifytheofficeinPart4soeachbeneficiaryavisaoradmitted: boolean = false;
  page_2_4_ChangethestatusandextendthestayofeachbeneficiarybecausethebeneficiaryisarenowintheUnitedStatesinanotherstatus: boolean = false;
  page_2_4_Extentdthestayofeachbeficiarynowholdthisstatus: boolean = false;
  page_2_4_Amendthestayofeachbeneficiarybecausethebeneficiarynowholdthisstatus: boolean = false;
  page_2_4_Extendthestatusofanonimmigrationclassificationbasedonafreetradeagreement: boolean = false;
  page_2_4_Changestatustoanonimmigrantclassificationbasedonafreetradeagreement: boolean = false;
  page_2_5_Totalnumberofworkersincludedinthispetition: string;
  page_2_1_IfanEntertainmentGroupProvidetheGropName: string;
  page_2_2_FamilyName: string;
  page_2_2_GivenName: string;
  page_2_2_MiddleName: string;
  page_2_3_FamilyName: string;
  page_2_3_GivenName: string;
  page_2_3_MiddleName: string;
  page_2_4_Dateofbirth: string;
  page_2_4_Male: boolean = false;
  page_2_4_Female: boolean = false;
  page_2_4_USSocialSecurityNumber: string;
  page_3_1_AlienRegistrationNumber: string;
  page_3_1_CountryofBirth: string;
  page_3_1_ProvinceofBirth: string;
  page_3_1_CountryofCitizenshiporNarionality: string;
  page_3_5_DateofLastArrival: string;
  page_3_5_I94ArrivalDepartureRecordNumber: string;
  page_3_5_PassportorTravelDocumentNumber: string;
  page_3_5_DatePassportorTravelDocument: string;
  page_3_5_DatePassportorTravelDocumentIssued: string;
  page_3_5_DatePassportorTravelDocumentExpires: string;
  page_3_5_PassportorTravelDocumentCountryofIssuance: string;
  page_3_5_CurrentNonimmigrantStatus: string;
  page_3_5_DateStatusExpiresorDS: string;
  page_3_5_StudentandExchangeVisitorInformationSystem: string;
  page_3_5_EmployementAuthorizationDocumentNumber: string;
  page_3_6_StreetNumberandName: string;
  page_3_6_Apt: boolean = false;
  page_3_6_Ste: boolean = false;
  page_3_6_Flr: boolean = false;
  page_3_6_Number: string;
  page_3_6_CityorTown: string;
  page_3_6_State: string;
  page_3_6_ZIPCode: string;
  page_3_1_Consulate: boolean = false;
  page_3_1_Preflightinspection: boolean = false;
  page_3_1_PortofEntry: boolean = false;
  page_3_1_OfficeAddress: string;
  page_3_1_USStateorForeignCiuntry: string;
  page_3_1_StreetNumberandName: string;
  page_3_1_Apt: boolean = false;
  page_3_1_Ste: boolean = false;
  page_3_1_Flr: boolean = false;
  page_3_1_Number: string;
  page_3_1_CityorTown: string;
  page_3_1_State: string;
  page_3_1_Province: string;
  page_3_1_PostalCode: string;
  page_3_1_Country: string;
  page_3_1_Yes: boolean = false;
  page_3_1_NoIfnogotoPart9andtypeorprintyourexplanation: boolean = false;
  page_4_3_Yes: boolean = false;
  page_4_3_Ifyeshowmany: string;
  page_4_3_No: boolean = false;
  page_4_4_Yes: boolean = false;
  page_4_4_Ifyeshowmany: string;
  page_4_4_No: boolean = false;
  page_4_5_Yes: boolean = false;
  page_4_5_Ifyeshowmany: string;
  page_4_5_No: boolean = false;
  page_4_6_YesIfyesproceedtoPart9andlistthebeneficiarysname: boolean = false;
  page_4_6_No: boolean = false;
  page_4_7_Yes: boolean = false;
  page_4_7_Ifyeshowmany: string;
  page_4_7_No: boolean = false;
  page_4_8_YesIfyesanswerthequetionsbelow: boolean = false;
  page_4_8_NoIfnoproceedItemNumber9: boolean = false;
  page_4_8_YesIfyesproceedtoPart9andtypeorprintyourexplanation: boolean = false;
  page_4_8_No: boolean = false;
  page_4_8_YesIfyesproceedtoPart9andtypeorprintyourexplanation_Hasanybeneficiaryinthispetititoneverbeengiven: boolean = false;
  page_4_8_No_Hasanybeneficiaryinthispetititoneverbeengiventheclassificationyournowrequestingwithinthelastsevenyears: boolean = false;
  page_4_9_YesIfyesproceedtoPart9andtypeorprintyourexplanation: boolean = false;
  page_4_9_No: boolean = false;
  page_4_10_YesIfyesproceedtoPart9andtypeorprintyourexplanation: boolean = false;
  page_4_10_No: boolean = false;
  page_4_11_YesIfyesproceedtoItemNumber11b: boolean = false;
  page_4_11_No: boolean = false;
  page_4_11_IfyoucheckedyesinItemNumber11aprovidethedatesthebeneficiarymaintaindestatusasaJ1exchangevisitororj2dependent: string;
  page_4_1_JobTitle: string;
  page_4_2_LCAorETACaseNumber: string;
  Page_05_1_JobTitle: string;
  Page_05_2_LCAorETACaseNumber: string;
  Page_05_3_StreetNumberandName: string;
  Page_05_3_Apt: boolean = false;
  Page_05_3_Ste: boolean = false;
  Page_05_3_Flr: boolean = false;
  Page_05_3_Number: string;
  Page_05_3_CityorTown: string;
  Page_05_3_State: string;
  Page_05_3_Zipcode: string;
  Page_05_4_Yes: boolean = false;
  Page_05_4_No: boolean = false;
  Page_05_5_Yes: boolean = false;
  Page_05_5_No: boolean = false;
  Page_05_6_Yes: boolean = false;
  Page_05_6_No: boolean = false;
  Page_05_7_Yes: boolean = false;
  Page_05_7_No: boolean = false;
  Page_05_8_IftheanswertoItemNumber7isnohowmanyhoursperweekfortheposition: string;
  Page_05_9_Wages: string;
  Page_05_9_per: string;
  Page_05_10_OtherCompensation: string;
  Page_05_11_DatesofintendedemploymentFrom: string;
  Page_05_11_From: string;
  Page_05_11_To: string;
  Page_05_12_TypeofBusiness: string;
  Page_05_13_YearEstablished: string;
  Page_05_14_CurrentNumberofEmployeesintheUnitedStates: string;
  Page_05_15_GrossAnnualIncome: string;
  Page_05_16_NetAnnualIncome: string;
  Page_05_1_AlicenseisnotrequiredfromeitherUSDepartmentofCommerceorUSDepartmentofState: boolean = false;
  Page_05_2_AlicenseisrequiredfromtheUSDepartmentofCommerceorUSDepartmentofState: boolean = false;
  Page_06_1_FamilyName: string;
  Page_06_1_GivenName: string;
  Page_06_1_Title: string;
  Page_06_2_SignatureofAuthorizedSignatory: string;
  Page_06_DateofSignature: string;
  Page_07_DaytimeTelephoneNumber: string;
  Page_07_EmailAddress: string;
  Page_06_1_FamilyName_Lastname: string;
  Page_06_1_GivenName_FirstName: string;
  Page_06_2_PreparersBusinessorOrganizationName: string;
  Page_07_3_StreetNumberandName: string;
  Page_07_3_Apt: boolean = false;
  Page_07_3_Ste: boolean = false;
  Page_07_3_Flr: boolean = false;
  Page_07_3_Number: string;
  Page_07_3_CityorTown: string;
  Page_07_3_State: string;
  Page_07_3_ZipCode: string;
  Page_07_3_Province: string;
  Page_07_3_PostalCode: string;
  Page_07_3_Country: string;
  Page_07_4_DaytimeTelephoneNumber: string;
  Page_07_4_FaxNumber: string;
  Page_07_4_EmailAddress: string;
  Page_07_5_SignatureofPreparer: string;
  Page_07_5_DateofSignature: string;
  Page_08_1_ANumber: string;
  page_08_2_r1_PageNumber: string;
  page_08_2_r1_PartNumber: string;
  page_08_2_r1_ItemNumber: string;
  page_08_2_addditionalinfo1: string;
  page_08_3_r2_PageNumber: string;
  page_08_3_r2_PartNumber: string;
  page_08_3_r2_ItemNumber: string;
  page_08_3_addditionalinfo2: string;
  page_08_4_r3_PageNumber: string;
  page_08_4_r3_PartNumber: string;
  page_08_4_r3_ItemNumber: string;
  page_08_4_addditionalinfo3: string;
  page_9_1_NameofthePetitioner: string;
  page_9_2_FamilyName: string;
  page_9_2_GivenName: string;
  page_9_2_MiddleName: string;
  page_9_3_E1TreatyTrader: boolean = false;
  page_9_3_E2TreatyInvestor: boolean = false;
  page_9_3_E2CNMIInvestor: boolean = false;
  page_9_4_NameofthecountrysignatorywiththeUnitedStates: string;
  page_9_5_Yes: boolean = false;
  page_9_5_No: boolean = false;
  page_9_1_EmployersName: string;
  page_9_2_TotalNumberofEmployees: string;
  page_9_3_StreetNumberandName: string;
  page_9_3_Apt: boolean = false;
  page_9_3_Ste: boolean = false;
  page_9_3_Flr: boolean = false;
  page_9_3_Number: string;
  page_9_3_CityorTown: string;
  page_9_3_State: string;
  page_9_3_ZIPCode: string;
  page_9_3_Province: string;
  page_9_3_PostalCode: string;
  page_9_3_Country: string;
  page_9_4_PrincipalProductMerchandiseorService: string;
  page_9_5_EmployeesPositionTitledutiesandnumberofyearsemployed: string;
  page_10_1_Parent: boolean = false;
  page_10_1_Branch: boolean = false;
  page_10_1_Subsidiary: boolean = false;
  page_10_1_Affiliate: boolean = false;
  page_10_1_JointVenture: boolean = false;
  page_10_2_PlaceofIncorporationorEstablishmentintheUnitedStates: string;
  page_10_2_DateofIncorporationorEstablishment: string;
  page_10_3_Name: string;
  page_10_3_Nationality: string;
  page_10_3_ImmigrationStatus: string;
  page_10_3_PercentofOwnership: string;
  page_10_4_Assets: string;
  page_10_5_NetWorth: string;
  page_10_6_NetAnnualIncome: string;
  page_10_7_Howmanyexecutiveandmanagerialemployees: string;
  page_10_7_Howmanypersonswithspecialqualifications: string;
  page_10_7_ProvidethetotalnumberofemployeesinexecutiveandmanagerialpositionsintheUnitedStates: string;
  page_10_7_ProvidethetotalnumberofemployeesintheUnitedStatesthatrequirepersonswithspecialqualifications: string;
  page_10_8_Ifthepetitionerisattemptingtoqualitytheemployeeasanexecutiveormanagerprovidethetotalnumberofemployees: string;
  page_10_1_TotalAnnualGrossTradeBusinessoftheUScompany: string;
  page_10_2_ForYearEnding: string;
  page_10_3_PercentoftotalGrossTradebetweentheUnitedStatesandthetreatytradercountry: string;
  page_10_1_Cash: string;
  page_10_1_Equipment: string;
  page_10_1_Other: string;
  page_10_1_Inventory: string;
  page_10_1_Premises: string;
  page_10_1_Total: string;
  Page_11_1_NameofthePetitioner: string;
  Page_11_2_NameoftheBeneficiary: string;
  Page_11_3_USEmployer: boolean = false;
  Page_11_3_ForeignEmployer: boolean = false;
  Page_11_3_IfForeignEmployerNametheForeignCountry: boolean = false;
  Page_11_1_FreeTradeCanada: boolean = false;
  Page_11_1_FreeTradeMexico: boolean = false;
  Page_11_1_FreeTradeChile: boolean = false;
  Page_11_1_FreeTradeSingapore: boolean = false;
  Page_11_1_FreeTradeOther: boolean = false;
  Page_11_1_AsixthconsecutiverequestforFreeTradeChileorSingapore: boolean = false;
  Page_11_1_FamilyName: string;
  Page_11_1_GivenName: string;
  Page_11_2_SignatureofPetitioner: string;
  Page_11_2_DateofSignature: string;
  Page_11_3_DaytimeTelephoneNumber: string;
  Page_11_3_MobileTelephoneNumber: string;
  Page_11_3_EmailAddress: string;
  Page_12_1_FamilyName: string;
  Page_12_1_GivenName: string;
  Page_12_2_PreparersBusinessorOrganizationName: string;
  Page_12_3_StreetNumberandName: string;
  Page_12_3_Apt: boolean = false;
  Page_12_3_Ste: boolean = false;
  Page_12_3_Flr: boolean = false;
  Page_12_3_Number: string;
  Page_12_3_CityorTown: string;
  Page_12_3_State: string;
  Page_12_3_ZIPCode: string;
  Page_12_3_Province: string;
  Page_12_3_PostalCode: string;
  Page_12_3_Country: string;
  Page_12_4_DaytimeTelephoneNumber: string;
  Page_12_4_FaxNumber: string;
  Page_12_4_EmailAddress: string;
  Page_12_5_SignatureofPreparer: string;
  Page_12_5_DateofSignature: string;

  Page_13_1_NameofthePetitioner: string;
  Page_13_2_NameoftheBeneficiary: string;
  Page_13_2_Providethetotalnumberofbeneficiaries: string;
  Page_13_3_ListeachbeneficiariespriorperiodsofstayinHorLclassificationintheUnitedeStatesforthelastsixyears: string;
  Page_13_4_H1BspecialtyOccupation: boolean = false;
  Page_13_4_H1B1ChileandSingapore: boolean = false;
  Page_13_4_H1B2ExceptionalservicesrelatingtoacooperativeresearchanddevelopmentprojectadministeredbytheUSDepartmentofDefense: boolean = false;
  Page_13_4_H1B3Fashionmodelofdistinguishedmeritandability: boolean = false;
  Page_13_4_H2AAgriculturalworker: boolean = false;
  Page_13_4_H2BNonAgriculturalworker: boolean = false;
  Page_13_4_H3Trainee: boolean = false;
  Page_13_4_H3Specialeducationexchangevisitorprogram: boolean = false;
  Page_13_5_Yes: boolean = false;
  Page_13_5_No: boolean = false;
  Page_13_6_Yes: boolean = false;
  Page_13_6_No: boolean = false;
  Page_13_7_YesIfyespleaseexplaininItemNumber7b: boolean = false;
  Page_13_7_No: boolean = false;
  Page_14_7_Explanation: string;
  Page_14_1_Describetheproposedduties: string;
  Page_14_2_Describethebeneficiaryspresentoccupationandsummaryofpriorworkexperience: string;
  Page_14_2_SignatureofPetitioner: string;
  Page_14_2_NameofPetitioner: string;
  Page_14_2_Date: string;
  Page_14_2_SignatureofAuthorizedOfficialofEmployer: string;
  Page_14_2_NameofAuthorizedOfficialofEmployer: string;
  Page_14_2_Date_StatementforH1BSpecialityOccupationandUSDepartmentofDefenseProjects: string;
  Page_14_2_SignatureofDODProjectManager: string;
  Page_14_2_NameofDODManager: string;
  Page_14_2_Date_StatementforH1BUSDepartmentofDefenseProjectsOnly: string;
  Page_14_1_Seasonal: boolean = false;
  Page_14_2_Peakload: boolean = false;
  Page_14_2_Intermittent: boolean = false;
  Page_14_2_Onetimeoccurence: boolean = false;
  Page_14_2_Unpredictable: boolean = false;
  Page_14_2_Periodic: boolean = false;
  Page_14_2_Recurrentanually: boolean = false;
  Page_15_3_EXplainyourtemporaryneedfortheworkersservices: string;
  Page_15_4_ListthecountriesofcitizenshipfortheH2AorH2Bworkersyouplantohire: string;
  page_15_4_a: string;
  page_15_4_b: string;
  page_15_4_c: string;
  page_15_4_d: string;
  page_15_4_e: string;
  page_15_4_f: string;
  Page_15_5_FamilyName: string;
  Page_15_5_GivenName: string;
  Page_15_5_MiddleName: string;
  Page_15_5_FamilyName_Provideallothernameused: string;
  Page_15_5_GivenName_Provideallothernameused: string;
  Page_15_5_MiddleName_Provideallothernameused: string;
  Page_15_5_DateofBirth: string;
  Page_15_5_CountryofBirth: string;
  Page_15_5_CountryofCitizenshiporNationality: string;
  Page_15_6_YesIfyesgotoPart9ofForm1129andwriteyourexplanation: boolean = false;
  Page_15_6_No: boolean = false;
  Page_15_6_VisaClassification: string;
  Page_15_7_Yes: boolean = false;
  Page_15_7_No: boolean = false;
  Page_15_7_Name: string;
  Page_16_7_StreetNumberandName: string;
  Page_16_7_Apt: boolean = false;
  Page_16_7_Ste: boolean = false;
  Page_16_7_Flr: boolean = false;
  Page_16_7_Number: string;
  Page_16_7_CityorTown: string;
  Page_16_7_State: string;
  Page_16_7_ZipCode: string;
  Page_16_8_Yes: boolean = false;
  Page_16_8_No: boolean = false;
  Page_16_8_Ifyeslistthetypesandamountsoffeesthattheworkerpaidorwillpay: string;
  Page_16_8_Yes_Iftheworkerspaidanyfeeorcompensationweretheyreimbursed: boolean = false;
  Page_16_8_No_Iftheworkerspaidanyfeeorcompensationweretheyreimbursed: boolean = false;
  Page_16_8_Yes_Iftheworkersagreedtopayafeethattheyhavenotyetbeenpaidhastheiragreementbeenterminatedbeforetheworkerspaidthefee: boolean = false;
  Page_16_8_No_Iftheworkersagreedtopayafeethattheyhavenotyetbeenpaidhastheiragreementbeenterminatedbeforetheworkerspaidthefee: boolean = false;
  Page_16_9_Yes: boolean = false;
  Page_16_9_No: boolean = false;
  Page_16_10_Yes_HaveyoueverhadanH2Aorh2Bpetitionedeniedorrevokedbecauseanemployeepaidajobplacement: boolean = false;
  Page_16_10_No_HaveyoueverhadanH2Aorh2Bpetitionedeniedorrevokedbecauseanemployeepaidajobplacement: boolean = false;
  Page_16_10_Ifyeswhen: string;
  Page_16_10_ReceiptNumber: string;
  Page_16_10_Yes_Weretheworkersreimbursedforsuchfeeandcompensation: boolean = false;
  Page_16_10_No_Weretheworkersreimbursedforsuchfeeandcompensation: boolean = false;
  Page_16_11_Yes: boolean = false;
  Page_16_11_No: boolean = false;
  Page_16_12_Yes: boolean = false;
  Page_16_12_No: boolean = false;
  Page_16_12_IfyesprovidetheEverifyCompanyIDorClientCompanyID: string;
  Page_17_1_SignatureofPetitioner: string;
  Page_17_1_NameofthePetitioner: string;
  Page_17_1_Date_Petitioner: string;
  Page_17_1_SignatureofEmployer: string;
  Page_17_1_NameofEmployer: string;
  Page_17_1_Date: string;
  Page_17_1_r1_SignatureofJointEmployer: string;
  Page_17_1_r1_NameofjointEmployer: string;
  Page_17_1_r1_Date: string;
  Page_17_1_r2_SignatureofJointEmployer: string;
  Page_17_1_r2_NameofjointEmployer: string;
  Page_17_1_r2_Date: string;
  Page_17_1_r3_SignatureofJointEmployer: string;
  Page_17_1_r3_NameofjointEmployer: string;
  Page_17_1_r3_Date: string;
  Page_17_1_r4_SignatureofJointEmployer: string;
  Page_17_1_r4_NameofjointEmployer: string;
  Page_17_1_r4_Date: string;
  Page_18_1_Yes: boolean = false;
  Page_18_1_No: boolean = false;
  Page_18_2_Yes: boolean = false;
  Page_18_2_No: boolean = false;
  Page_18_3_Yes: boolean = false;
  Page_18_3_No: boolean = false;
  Page_18_4_Yes: boolean = false;
  Page_18_4_No: boolean = false;
  Page_18_5_Yes: boolean = false;
  Page_18_5_No: boolean = false;
  Page_18_6_Yes: boolean = false;
  Page_18_6_No: boolean = false;
  Page_18_7_Ifyoudonotintedtoemploythebeneficiaryabroadattheendofthistrainingexplainwhyyouwishtoincurthecostofprovidingthis: string;

  Page_19_1_Nameofthepetitioner: string;
  Page_19_2_NameoftheBeneficiary: string;
  Page_19_1_Yes: boolean = false;
  Page_19_1_No: boolean = false;
  Page_19_1_Yes_hasthepetitionereverbeenfoundtobeawillfulviolator: boolean = false;
  Page_19_1_No_hasthepetitionereverbeenfoundtobeawillfulviolator: boolean = false;
  Page_19_1_Yes_IsthebeneficiaryandH1BnonimmigrantexemptfromtheDepartmentofLaboreattestationrequrement: boolean = false;
  Page_19_1_No_IsthebeneficiaryandH1BnonimmigrantexemptfromtheDepartmentofLaboreattestationrequrement: boolean = false;
  Page_19_1_Yes_Ifyesisitbecausethebeneficiarysannualrateofpayisequaltoatleast60000: boolean = false;
  Page_19_1_No_Ifyesisitbecausethebeneficiarysannualrateofpayisequaltoatleast60000: boolean = false;
  Page_19_1_Yes_Oritisthebecausethebeneficiaryshasamastersdegreeorhigherdegreeinaspecialityrelatedtotheemployement: boolean = false;
  Page_19_1_No_Oritisthebecausethebeneficiaryshasamastersdegreeorhigherdegreeinaspecialityrelatedtotheemployement: boolean = false;
  Page_19_1_Yes_Doesthepetitioneremploy50ormoreindividualsintheUnitedStates: boolean = false;
  Page_19_1_No_Doesthepetitioneremploy50ormoreindividualsintheUnitedStates: boolean = false;
  Page_19_1_Yes_Ifyesaremorethan50percentofthoseemployeesinH1BL1AL1Bnonimmigrantstatus: boolean = false;
  Page_19_1_No_Ifyesaremorethan50percentofthoseemployeesinH1BL1AL1Bnonimmigrantstatus: boolean = false;
  Page_19_2_NODIPLOMA: boolean = false;
  Page_19_2_HIGHSCHOOLGRADUATEDIPLOMAortheequivalent: boolean = false;
  Page_19_2_Somecollegecreditbutlessthan1year: boolean = false;
  Page_19_2_Oneormoreyearsofcollegenodegree: boolean = false;
  Page_19_2_Associatesdegree: boolean = false;
  Page_19_2_Bachelorsdegree: boolean = false;
  Page_19_2_Mastersdegree: boolean = false;
  Page_19_2_Professionaldegree: boolean = false;
  Page_19_2_Doctoratedegree: boolean = false;
  Page_19_3_MajorPrimaryfieldofstudy: string;
  Page_19_4_RateofPayPerYear: string;
  Page_19_5_DOTCode: string;
  Page_19_6_NAICSCode: string;
  Page_19_1_Yes_Areyouaninstitutionofhighereducationasdefinedinsection10oftheHigherEducaionActof196520USC1001: boolean = false;
  Page_19_1_No_Areyouaninstitutionofhighereducationasdefinedinsection10oftheHigherEducaionActof196520USC1001: boolean = false;
  Page_19_2_Yes: boolean = false;
  Page_19_2_No: boolean = false;
  Page_20_3_Yes: boolean = false;
  Page_20_3_No: boolean = false;
  Page_20_4_Yes: boolean = false;
  Page_20_4_No: boolean = false;
  Page_20_5_Yes: boolean = false;
  Page_20_5_No: boolean = false;
  Page_20_6_Yes: boolean = false;
  Page_20_6_No: boolean = false;
  Page_20_7_Yes: boolean = false;
  Page_20_7_No: boolean = false;
  Page_20_8_Yes: boolean = false;
  Page_20_8_No: boolean = false;
  Page_20_9_Yes: boolean = false;
  Page_20_9_No: boolean = false;
  Page_20_1_CAPH1BBachelorsDegree: boolean = false;
  Page_20_1_CAPH1BUSMastersDegreeorHigher: boolean = false;
  Page_20_1_CAPH1BChileSingapore: boolean = false;
  Page_20_1_CAPExempt: boolean = false;
  Page_20_2_NameoftheUnitedStatesInstitutionorHigherEducation: string;
  Page_20_2_DateDegreeAwarded: string;
  Page_20_2_TypeofUnitedStatesDegree: string;
  Page_20_2_StreetNumberandName: string;
  Page_20_2_Apt: boolean = false;
  Page_20_2_Ste: boolean = false;
  Page_20_2_Flr: boolean = false;
  Page_20_2_Number: string;
  Page_20_2_CityorTown: string;
  Page_20_2_State: string;
  Page_20_2_ZIPCode: string;
  Page_21_3_Thepetitionerisaninstitutionofhighereducationasdefinedinsection101oftheHigherEducationActof196520USC1001: boolean = false;
  Page_21_3_Thepetitionerisanonprofitentityrelatedtooraffiliatedwithaninstitutionofhighereducationasdefinedin8CFR2142: boolean = false;
  Page_21_3_Thepetitionerisanonprofitresearchorganizationoragovernmentalreserachorganizztionasdefinedin8CFR2142: boolean = false;
  Page_21_3_Thebeneficiarywillbeemployedataqualifyingcapexemptinstitutionorganizationorentitypursuantto8CFR2142: boolean = false;
  Page_21_3_ThepetitionerisrequestinganamendmenttoorextensionofstayforthebenefiicaryscurrentH1Bclassification: boolean = false;
  Page_21_3_ThebeneficiaryofthispetitionisaJ1nonimmigrantphysicianwhohasreceivedawaiverbasedonsection214oftheAct: boolean = false;
  Page_21_3_Thebeneficiaryofthispetitonhasbeencountedagainstthecapandisapplyingfoetheremainingprotion: boolean = false;
  Page_21_3_ThepetitionerisanemployersubjecttotheGuamCNMIcapextensionpursuanttoPublicLaw110229: boolean = false;
  Page_21_1_Yes: boolean = false;
  Page_21_1_No: boolean = false;
  Page_21_2_Yes: boolean = false;
  Page_21_2_No: boolean = false;
  Page_21_3_Yes: boolean = false;
  Page_21_3_No: boolean = false;
  Page_22_1_NameofthePetetioner: string;
  Page_22_2_NameoftheBeneficiary: string;
  Page_22_3_Anindividualpetition: boolean = false;
  Page_22_4_Ablanketpetition: boolean = false;
  Page_22_4_Yes: boolean = false;
  Page_22_4_No: boolean = false;
  Page_22_4_Yes_Ifyesaremorethan50percentofthoseemployeeinH1BL1AorL1Bnonimmigrantstates: boolean = false;
  Page_22_4_No_Ifyesaremorethan50percentofthoseemployeeinH1BL1AorL1Bnonimmigrantstates: boolean = false;
  Page_22_1_L1Amanagerorexecutive: boolean = false;
  Page_22_1_L1Bspecializedknowledge: boolean = false;
  Page_22_2_SubjectsName: string;
  page_22_2_PeriodofStay: string;
  Page_22_3_NameofEmployerAbroad: string;
  Page_22_4_StreetNumberandName: string;
  Page_22_4_Apt: boolean = false;
  Page_22_4_Ste: boolean = false;
  Page_22_4_Flr: boolean = false;
  Page_22_4_Number: string;
  Page_22_4_CityorTown: string;
  Page_22_4_State: string;
  Page_22_4_ZIPCode: string;
  Page_22_4_Province: string;
  Page_22_4_PostalCode: string;
  Page_22_4_Country: string;
  Page_23_5_DatesofEmployment: string;
  Page_23_5_ExplainofInterruptions: string;
  Page_23_6_Describethebeneficiarysdutiesabroadforthe3yearsprecedingthefillingofthepetition: string;
  Page_23_7_DescribethebeneficiarysproposeddutiesintheUnitedStates: string;
  Page_23_8_Summarizethebeneficiaryseducationandworkexperience: string;
  Page_23_9_Parent: boolean = false;
  Page_23_9_Branch: boolean = false;
  Page_23_9_Subsidary: boolean = false;
  Page_23_9_Affiliate: boolean = false;
  Page_23_9_JointVenture: boolean = false;
  Page_24_10_Percentageofcompanystockownershipandmanagerialcontrolofeachcompanythathasaqualifyingrelationship: string;
  Page_24_10_FederalEmployerIdentificationNumberforeachUscompanyththasaqualifyingrelationship: string;
  Page_24_11_Yes: boolean = false;
  Page_24_11_NoifnoprovideanexplanationinPart9ofFormI129thattheUScompanyhasandwillhaveaqualifyingrelationship: boolean = false;
  Page_24_12_Yes: boolean = false;
  Page_24_12_No: boolean = false;
  page_24_13_Yes: boolean = false;
  page_24_13_No: boolean = false;
  Page_24_13_Ifyouansweredyestotheprecedingquestiondescribehowandbywhomthebeneficiaryswork: string;
  Page_24_13_Ifyouansweredyestotheprecedingquestiondescribethereasonswhyplacementatanotherwork: string;
  Page_25_1_NameandAddress: string;
  Page_25_1_Relationship: string;

  Page_26_1_Nameofthepetitioner: string;
  Page_26_2_NameoftheBeneficiary: string;
  Page_26_2_Providethetotalnumberofbeneficiaries: string;
  Page_26_3_O1AAlienofextraordinaryabilityinscienceseducationbusinessorathletics: boolean = false;
  Page_26_3_O1BAlienofextraordinaryabilityintheartsofextraordinaryachievementinthemotionpictureortelevisionindustry: boolean = false;
  Page_26_3_O2AccompanyingalienwhoiscomingtotheUnitedStatestoassistintheperformanceoftheO1: boolean = false;
  Page_26_3_P1MajorLeagueSports: boolean = false;
  Page_26_3_P1AthleteorAthleticEntertainmentGroup: boolean = false;
  Page_26_3_P1SEssentialSupportPersonnelforP1: boolean = false;
  Page_26_3_P2Artistorentertainerforreciprocalexchangeprogram: boolean = false;
  Page_26_3_P2SEssentialSupportPersonnelforP2: boolean = false;
  Page_26_3_p2ArtistEngineercomintotheUnitedStatestoperformteachorcoachunderaprogramthatisculturallyunique: boolean = false;
  Page_26_3_P3SEssentialSupportPersonnelforP3: boolean = false;
  Page_26_4_Explainthenatureoftheevent: string;
  Page_26_5_Describethedutiestobeperformed: string;
  Page_26_6_IffillingforanO2orPsupportclassificationlistdatesofthebeneficiaryspriorworkexperienceundertheprincipalO1orPalien: string;
  Page_26_7_YesIfyespleaseexplaininItemNumber7b: boolean = false;
  Page_26_7_No: string;
  Page_27_7_Explanation: string;
  Page_27_8_Yes: boolean = false;
  Page_27_8_NoIfnoproceedtoPart9andtypeorprintyourexplanation: boolean = false;
  Page_27_9_Yes: boolean = false;
  Page_27_9_Nocopyofrequestedattach: boolean = false;
  Page_27_9_NA: boolean = false;
  Page_27_10_NameofRecognizedPeerPeerGrouporLaborOrganization: string;
  Page_27_10_StreetNumberandName: string;
  Page_27_10_Apt: boolean = false;
  Page_27_10_Ste: boolean = false;
  Page_27_10_Flr: boolean = false;
  Page_27_10_Number: string;
  Page_27_10_CityorTown: string;
  Page_27_10_State: string;
  Page_27_10_ZIPCode: string;
  Page_27_10_DateSent: string;
  Page_27_10_DaytimeTelephoneNumber: string;
  Page_27_11_NameoftheLaborOrganization: string;
  Page_27_11_StreetNumberandName: string;
  Page_27_11_Apt: boolean = false;
  Page_27_11_Ste: boolean = false;
  Page_27_11_Flr: boolean = false;
  Page_27_11_Number: string;
  Page_27_11_CityorTown: string;
  Page_27_11_State: string;
  Page_27_11_ZIPCode: string;
  Page_27_11_DateSent: string;
  Page_27_11_DaytimeTelephoneNumber: string;
  Page_27_12_NameofManagementOrganization: string;
  Page_27_12_StreetNumberandName: string;
  Page_27_12_Apt: boolean = false;
  Page_27_12_Ste: boolean = false;
  Page_27_12_Flr: boolean = false;
  Page_27_12_Number: boolean = false;
  Page_27_12_CityorTown: string;
  Page_27_12_State: string;
  Page_27_12_ZIPCode: string;
  Page_27_12_DateSent: string;
  Page_27_12_DaytimeTelephoneNumber: string;
  Page_28_13_NameofLaborOrganization: string;
  Page_28_13_StreetNumberandName: string;
  Page_28_13_Apt: boolean = false;
  Page_28_13_Ste: boolean = false;
  Page_28_13_Flr: boolean = false;
  Page_28_13_Number: string;
  Page_28_13_CityorTown: string;
  Page_28_13_State: string;
  Page_28_13_ZIPCode: string;
  Page_28_13_DateSent: string;
  Page_28_13_DaytimeTelephoneNumber: string;
  Page_28_1_FamilyName: string;
  Page_28_1_GivenName: string;
  Page_28_1_MiddleName: string;
  Page_28_2_SignatureofPetitioner: string;
  Page_28_2_DateofSignature: string;
  Page_28_3_DaytimeTelephoneNumber: string;
  Page_28_3_EmailAddress: string;
  I_129_VersionId: 1;
  Page_29_1_NameofthePetitioner: string;
  Page_29_2_NameoftheBeneficiary: string;
  Page_29_1_FamilyName: string;
  Page_29_1_GivenName: string;
  Page_29_1_MiddleName: string;
  Page_29_2_SignatureofPetitioner: string;
  Page_29_2_DateofSignature: string;
  Page_29_3_DaytimeTelephoneNumber: string;
  Page_29_3_EmailAddress: string;

  page_30_1_NameofthePetitioner: string;
  page_30_1_NameoftheBeneficiary: string;
  page_30_1_Numberofmembersofthepetitionerreligiousorganiztaion: string;
  page_30_1_Numberofemployeesworkingatthesamelocationwherethebeneficiarywillbeemployed: string;
  page_30_1_Numberofaliensholdingspecialimmigrantornonimmigrantreligiosworkerstatuscurrentlyemployedoremployedwhithinthe: string;
  page_30_1_Numberofspecialimmigrantreligiousworkspetitionandnonmmigtantreligiousworkerpetitionfiledbythepetition: string;
  page_30_2_Yes: boolean = false;
  page_30_2_No: boolean = false;
  page_30_2_AlienorDependentFamilyMembersName: string;
  page_30_2_PeriodofStay: string;
  page_31_3_Position: string;
  page_31_3_SummaryoftheTypeofResponsibilitiesforThatPosition: string;
  page_31_4_DescribetherelationshipifanybetweenthereligiousorganizationintheUnitedStatesandtheorganization: string;
  page_31_5_Titleofpositionoffered: string;
  page_31_5_Detaileddescriptionofthebeneficiarysproposeddailyduties: string;
  page_31_5_Descriptionofthebeneficiarysqualificationsforpositionsoffered: string;
  page_31_5_Descriptionoftheproposedsalariedcompensationornoncompensation: string;
  page_32_5_Listoftheaddressorlocationwherethebeneficiarywillbrworking: string;
  page_32_6_Yes: boolean = false;
  page_32_6_No: boolean = false;
  page_32_7_Yes: boolean = false;
  page_32_7_No: boolean = false;
  page_32_8_Yes: boolean = false;
  page_32_8_No: boolean = false;
  page_32_9_Yes: boolean = false;
  page_32_9_No: boolean = false;
  page_33_10_Yes: boolean = false;
  page_33_10_No: boolean = false;
  page_33_10_Explanation1: string;
  page_33_11_Yes: boolean = false;
  page_33_11_No: boolean = false;
  page_33_10_Explanation2: string;
  page_33_12_Yes: boolean = false;
  page_33_12_No: boolean = false;
  page_33_10_Explanation3: string;
  page_33_1_Nameofpetitioner: string;
  page_33_1_Title: string;
  page_33_1_Signatureofpetitioner: string;
  page_33_1_Date: string;
  page_33_1_EmployerorOrganizationName: string;
  page_34_1_StreetNumberandName: string;
  page_34_1_Apt: boolean = false;
  page_34_1_Ste: boolean = false;
  page_34_1_Flr: boolean = false;
  page_34_1_Number: string;
  page_34_1_CityorTown: string;
  page_34_1_State: string;
  page_34_1_ZIPCode: string;
  page_34_1_DaytimeTelephoneNumber: string;
  page_34_1_FaxNumber: string;
  page_34_1_EmailAddress: string;
  page_34_1_NameofEmployingOrganization: string;
  page_34_1_NameofReligiousDenomination: string;
  page_34_1_NameofAuthorizedrepresentativeofAttestingOrganization: string;
  page_34_1_Title: string;
  page_34_1_SignatureofAuthorizedRepresentativeofAttestingOrganization: string;
  page_34_1_Date: string;
  page_34_1_AttestingOrganizationName: string;
  page_34_1_StreetNumberandName_AttestationOrganizationNameandAddress: string;
  page_34_1_Apt_AttestationOrganizationNameandAddress: boolean = false;
  page_34_1_Ste_AttestationOrganizationNameandAddress: boolean = false;
  page_34_1_Flr_AttestationOrganizationNameandAddress: boolean = false;
  page_34_1_Number_AttestationOrganizationNameandAddress: string;
  page_34_1_CityorTown_AttestationOrganizationNameandAddress: string;
  page_34_1_State_AttestationOrganizationNameandAddress: string;
  page_34_1_ZIPCode_AttestationOrganizationNameandAddress: string;
  page_34_1_DaytimeTelephoneNumber_AttestationOrganizationNameandAddress: string;
  page_34_1_FaxNumber_AttestationOrganizationNameandAddress: string;
  page_34_1_EmailAddress_AttestationOrganizationNameandAddress: string;

  page_35_1_FamilyName: string;
  page_35_1_GivenName: string;
  page_35_1_MiddleName: string;
  page_35_1_Dateofbirth: string;
  page_35_1_Male: boolean = false;
  page_35_1_Female: boolean = false;
  page_35_1_USSocialsecurityNumber: string;
  page_35_1_ANumber: string;
  page_35_1_FamilyName_AllOtherNamesUsed: string;
  page_35_1_GivenName_AllOtherNamesUsed: string;
  page_35_1_MiddleName_AllOtherNamesUsed: string;
  page_35_1_StreetNumberandName: string;
  page_35_1_Apt: boolean = false;
  page_35_1_Ste: boolean = false;
  page_35_1_Flr: boolean = false;
  page_35_1_Number: string;
  page_35_1_CityorTown: string;
  page_35_1_State: string;
  page_35_1_ZIPCode: string;
  page_35_1_StreetNumberandName_ForeignAddress: string;
  page_35_1_Apt_ForeignAddress: boolean = false;
  page_35_1_Ste_ForeignAddress: boolean = false;
  page_35_1_Flr_ForeignAddress: boolean = false;
  page_35_1_Number_ForeignAddress: string;
  page_35_1_CityorTown_ForeignAddress: string;
  page_35_1_State_ForeignAddress: string;
  page_35_1_ZIPCode_ForeignAddress: string;
  page_35_1_Province: string;
  page_35_1_PostalCode: string;
  page_35_1_Country: string;
  page_35_1_CountryofBirth: string;
  page_35_1_CountryofCitizenshiporNationality: string;
  page_35_1_DateofLastArrival: string;
  page_35_1_I94ArrivalDepartureRecordNumber: string;
  page_35_1_PassportorTravelDocumentNumber: string;
  page_35_1_DatePassportorTravelDocumentIssued: string;
  page_35_1_DatePassportorTravelDocumentExpires: string;
  page_35_1_CountryofIssuancePassportororTravelorDocument: string;
  page_35_1_CurrentNonimmigrantStatus: string;
  page_35_1_DateStatusExpiresorDS: string;
  page_35_1_StudentandExchangeVisitorInformationSystemNumber: string;
  page_35_1_EmploymentAuthorizationDocumentNumber: string;
  page_36_1_FamilyName: string;
  page_36_1_GivenName: string;
  page_36_1_MiddleName: string;
  page_36_1_Dateofbirth: string;
  page_36_1_Male: boolean = false;
  page_36_1_Female: boolean = false;
  page_36_1_USSocialsecurityNumber: string;
  page_36_1_ANumber: string;
  page_36_1_FamilyName_AllOtherNamesUsed: string;
  page_36_1_GivenName_AllOtherNamesUsed: string;
  page_36_1_MiddleName_AllOtherNamesUsed: string;
  page_36_1_StreetNumberandName: string;
  page_36_1_Apt: boolean = false;
  page_36_1_Ste: boolean = false;
  page_36_1_Flr: boolean = false;
  page_36_1_Number: string;
  page_36_1_CityorTown: string;
  page_36_1_State: string;
  page_36_1_ZIPCode: string;
  page_36_1_StreetNumberandName_ForeignAddress: string;
  page_36_1_Apt_ForeignAddress: boolean = false;
  page_36_1_Ste_ForeignAddress: boolean = false;
  page_36_1_Flr_ForeignAddress: boolean = false;
  page_36_1_Number_ForeignAddress: string;
  page_36_1_CityorTown_ForeignAddress: string;
  page_36_1_State_ForeignAddress: string;
  page_36_1_ZIPCode_ForeignAddress: string;
  page_36_1_Province: string;
  page_36_1_PostalCode: string;
  page_36_1_Country: string;
  page_36_1_CountryofBirth: string;
  page_36_1_CountryofCitizenshiporNationality: string;
  page_36_1_DateofLastArrival: string;
  page_36_1_I94ArrivalDepartureRecordNumber: string;
  page_36_1_PassportorTravelDocumentNumber: string;
  page_36_1_DatePassportorTravelDocumentIssued: string;
  page_36_1_DatePassportorTravelDocumentExpires: string;
  page_36_1_CountryofIssuancePassportororTravelorDocument: string;
  page_36_1_CurrentNonimmigrantStatus: string;
  page_36_1_DateStatusExpiresorDS: string;
  page_36_1_StudentandExchangeVisitorInformationSystemNumber: string;
  page_36_1_EmploymentAuthorizationDocumentNumber: string;
}
